### ISSUE TITLE
ADB mode

### ISSUE THREAD

**Issue by NSTAdventure** [Jasper-1024/DeepSleep#4]
Bruh you should add ADB mode 

Because with basic knowledge of ADB you can disable WAKE_LOCK permission using app ops

Realme 5i
RMX 2030
Android 10 Realme UI 1.0

**Comment by Jasper-1024** [comment]
Maybe [appops](https://appops.rikka.app/)  has already done this

**Comment by NSTAdventure** [comment]
> Maybe [appops](https://appops.rikka.app/) has already done this

H*ll no they not foss I don't want to use it that's why i request to you to add ADB mode 🙏

**Comment by Jasper-1024** [comment]
> > Maybe [appops](https://appops.rikka.app/) has already done this
> 
> H*ll no they not foss I don't want to use it that's why i request to you to add ADB mode pray
I need to prioritize my life and work dilemma now.
When I have time for deepsleep I would like to refactor the code, but it is still a priority to improve the functionality under xposed, and if it goes well I would like to consider adding other features, but I can't commit to a specific timeline.

**Comment by NSTAdventure** [comment]
uh sir hy closed? @Jasper-1024
