### ISSUE TITLE
开关表达意思不明确

### ISSUE THREAD

**Issue by myselfghost** [Jasper-1024/DeepSleep#6]
在deepsleep app 列表显示页面，点按app图标出现的开关，开关默认打在右边，这样是允许后台服务，还是不允许后台服务？

![20220705-165826.jpg](https://img1.imgtp.com/2022/07/05/jgRDp1o5.jpg)

**Comment by Jasper-1024** [comment]
开关两种状态差别挺明显的,默认是开状态,点击则为关闭...并没有感觉有反直觉的地方...

如果有这个困扰,或许在 应用名 后面,开关 上面 再加一个 text 再提示一下?

**Comment by myselfghost** [comment]
> 开关两种状态差别挺明显的,默认是开状态,点击则为关闭...并没有感觉有反直觉的地方...
> 
> 如果有这个困扰,或许在 应用名 后面,开关 上面 再加一个 text 再提示一下?
右边是开关“开”状态倒是没有反直觉。
按照手机权限授权的常规思路，开关“开”状态是“允许”该操作。然而在DeepSleep，开关“开”是“不允许”或者是“限制”？

**Comment by ajmz** [comment]
> 开关两种状态差别挺明显的,默认是开状态,点击则为关闭...并没有感觉有反直觉的地方...
> 
> 如果有这个困扰,或许在 应用名 后面,开关 上面 再加一个 text 再提示一下?

确实有点迷惑，请问假如只在需要时才手动启动APP，即最严格限制应用后台行为，那么这四个开关都要关闭吗？
另外建议整体操作和四种开关分别操作，这五种情况，增加批量选择APP进行开关的功能。
现在LSPosed作用域选择需要限制应用，但还需要在DeepSleep里面逐个开关关闭，麻烦了。

**Comment by Jasper-1024** [comment]
> 

1. 最严格限制确实是需要 开关都要关.
2. 批量选取操作,受限于对android ui 的了解,目前暂时无法在现有代码完成.
3. LSPosed作用域选择 无法在模块内操作,模块内只能硬编码建议选择应用...

对应解决:
1. 增加一个提示,这样 开关 应该没啥疑惑了.
2. 作用域的设计原本就是这样,只让 xposed 在有限的应用内生效. 或许可以添加一个实验选项,当应用安装时有一个默认的动作.

**Comment by Jasper-1024** [comment]
![613.png](https://img1.imgtp.com/2022/07/08/ETcYGMVd.png)

**Comment by ajmz** [comment]
看到NoWakeLock在酷安的更新，是比DeepSleep更复杂，希望DeepSleep也保持更新。
另外建议DeepSleep增加无障碍选项，以避免被其他进程管理应用误杀。

**Comment by Jasper-1024** [comment]
> 看到NoWakeLock在酷安的更新，是比DeepSleep更复杂，希望DeepSleep也保持更新。 另外建议DeepSleep增加无障碍选项，以避免被其他进程管理应用误杀。

1. 似乎现在想做的功能已经弄完了,有 bug 就修 bug 没bug 也就暂时不需要更新.
2. 无障碍功能属于滥用,play 商店就上不了了.再说 1.2 版本以后不再需要后台,不存在误杀的问题.
3. 这个 issue 时间太久没有结果,即将关闭,如果有新的需求/问题 请开新 issue
