### ISSUE TITLE
LSPosed permission

### ISSUE THREAD

**Issue by chaoscreater** [Jasper-1024/DeepSleep#7]
Let's say I have an app called 1.1.1.1 and I want to block the wakelocks for this app.

Would I just need to enable this app in the DeepSleep module in LSPosed, then disable wakelock under DeepSleep app?

![image](https://user-images.githubusercontent.com/18227319/191498763-c6d7047a-6109-4d74-8bc7-4f9c06c9ec34.png)

![image](https://user-images.githubusercontent.com/18227319/191498776-2dd339b4-fec7-43f3-b1d8-2d3d129b7337.png)

Is this correct?

**Comment by Jasper-1024** [comment]
there is no need select system framework.other select is enough.

**Comment by chaoscreater** [comment]
I'm selecting System Framework because there are some wakelocks that I need to block.
